### ISSUE TITLE
Add tracking

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#20]
- [ ] Change Google Analytics tag to the below.  Remove Google Tag Manager.
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75845088-1', 'auto');
  ga('send', 'pageview');

</script>
```

- [ ] Add this code to the header to send UTM Source, UTM Medium, and UTM Campaign with nomination and sign up submissions and a refcode with actblue urls

```
<script>
    function getParameterByName(name, url) {
      if (!url) {
        url = window.location.href;
      }
      name = name.replace(/[\[\]]/g, "\\$&");
      var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
          results = regex.exec(url);
      if (!results) return null;
      if (!results[2]) return '';
      return decodeURIComponent(results[2].replace(/\+/g, " "));
    }
    function trackSignup() {
      console.log('TRACKING SIGNUP')
      ga('send', 'event', 'SignupButton', 'click')
      return true;
    }
    function parseURL(url) {
      var a=document.createElement('a');
      a.href=url;
      return a.hostname;
    }
    function setUTMCodes() {
      var utmSource = getParameterByName('utm_source') || parseURL(document.referrer)
      var utmMedium = getParameterByName('utm_medium')
      var utmCampaign = getParameterByName('utm_campaign')
      var refCode = (utmCampaign ? (utmCampaign + "/") : "") + (utmSource ? utmSource : "") + (utmMedium ? ("/" + utmMedium) : "")
      var signupRedirects = document.querySelectorAll('[href="https://secure.actblue.com/contribute/page/jdsignup"]')
      for (var index = 0; index < signupRedirects.length; index++) {
        var signupRedirect = signupRedirects[index]
        signupRedirect.href = 'https://secure.actblue.com/contribute/page/jdsignup?refcode=' + refCode
      
      if (utmCampaign) {
        var campaignInputs = document.getElementsByName('utmCampaign');
        for (index = 0; index < campaignInputs.length; index++) {
          campaignInputs[index].value = utmCampaign
        }
      }
      if (utmSource) {
        var sourceInputs = document.getElementsByName('utmSource');
        for (index = 0; index < sourceInputs.length; index++) {
          sourceInputs[index].value = utmSource
        }
      }
      if (utmMedium) {
        var mediumInputs = document.getElementsByName('utmMedium');
        for (index = 0; index < mediumInputs.length; index++) {
          mediumInputs[index].setAttribute('value', utmMedium)
        }
      }
      var donateButtons = document.querySelectorAll('[href="https://secure.actblue.com/contribute/page/justicedemocrats"]')
      for (var index = 0; index < donateButtons.length; index++) {
       var donateButton = donateButtons[index]
       donateButton.href = 'https://secure.actblue.com/contribute/page/justicedemocrats?refcode=' + refCode
      }
    }
  </script>
```
The code above assumes some stuff that may not be how this site works.  It is attempting to look for hidden fields named 'utmCampaign', etc. to send those values along with form submissions.  And it's trying to update all actblue URLs based on queryparams.

- [ ]  Make sure that utmSource, utmMedium, and utmCampaign are being sent with sign up and nomination form submissions, and make sure refcode is being sent with all links to actblue (including post-signup).

- [ ] Add an onsubmit to the signup form that does `onsubmit="return trackSignup();"`

**Comment by chadwickmeyer** [comment]
This has been completed per spec.
